package tp0.modelo.dispositivo;

public enum DispositivoConcretoEnum{
	AIREACONDICIONADO_3500,
	AIREACONDICIONADO_2200,
	TELEVISOR_TUBO_21,
	TELEVISOR_TUBO_29_34,
	TELEVISOR_LCD_40,
	TELEVISOR_LED_24,
	TELEVISOR_LED_32,
	TELEVISOR_LED_40,
	HELADERA_CONFREEZER,
	HELADERA_SINFREEZER,
	LAVARROPAS_AUTO_5KG_CALENTAMIENTOAGUA,
	LAVARROPAS_AUTO_5KG,
	LAVARROPAS_SEMIAUTO_5KG,
	VENTILADOR_PIE,
	VENTILADOR_TECHO,
	LAMPARA_HALOGENA_40W,
	LAMPARA_HALOGENA_60W,
	LAMPARA_HALOGENA_100W,
	LAMPARA_11W,
	LAMPARA_15W,
	LAMPARA_20W,
	PC,
	MICROONDAS,
	PLANCHA;	
}


